# Generated by Django 5.1.6 on 2025-07-24 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actuality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuality',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Description de l'actualité"),
        ),
    ]
