# Generated by Django 5.2.4 on 2025-07-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuality', '0002_alter_actuality_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuality',
            name='intitule',
            field=models.CharField(blank=True, max_length=200, verbose_name='entrez les origines de vôtre source\xa0'),
        ),
        migrations.AddField(
            model_name='actuality',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name="Source de l'actualité"),
        ),
        migrations.AddField(
            model_name='actuality',
            name='type',
            field=models.CharField(choices=[('Politique', 'Politique'), ('Économie', 'Économie'), ('International', 'International'), ('Société', 'Société'), ('Santé', 'Santé'), ('Technologie', 'Technologie'), ('Environnement', 'Environnement'), ('Culture', 'Culture'), ('Sports', 'Sports'), ('Sciences', 'Sciences'), ('Éducation', 'Éducation'), ('Justice', 'Justice'), ('Evènement', 'Évènement'), ('Innovation', 'Innovation'), ('Podcast', 'Podcast')], default='Politique', max_length=100, verbose_name="Type d'actualité"),
        ),
    ]
