# Generated by Django 5.2.4 on 2025-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuality', '0003_actuality_intitule_actuality_source_actuality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuality',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hauteur'),
        ),
    ]
