# Generated by Django 5.1.6 on 2025-07-22 14:36

import django.db.models.deletion
import evenslide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.CharField(db_index=True, default=evenslide.models.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('intitule', models.CharField(max_length=300)),
                ('localisation', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=evenslide.models.media)),
                ('heur', models.TimeField()),
                ('prix', models.PositiveIntegerField(blank=True, default=0)),
                ('nb_place', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('nb_tickets', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('actions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evenslide.action')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evenslide.typeevenement')),
            ],
        ),
    ]
