# Generated by Django 5.1.6 on 2025-07-23 02:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenslide', '0002_alter_action_id_alter_typeevenement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
