# Generated by Django 5.2.4 on 2025-07-31 14:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titre de la section à propos')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'À propos',
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cookie',
                'verbose_name_plural': 'Les Cookies',
            },
        ),
        migrations.CreateModel(
            name='GeneralCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Conditions générales',
                'verbose_name_plural': 'Texte sur les conditions générales',
            },
        ),
        migrations.CreateModel(
            name='LegalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mention légale',
                'verbose_name_plural': 'Texte sur les mentions légales',
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Donnée personnelle',
                'verbose_name_plural': 'Texte sur les données personnelles',
            },
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_file', models.FileField(blank=True, upload_to='images/')),
                ('pub_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Publicités',
                'verbose_name_plural': 'Les Publicités',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('email', models.EmailField(max_length=254, verbose_name='Service email')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre du carroussel')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image du carroussel')),
                ('url', models.URLField(blank=True, verbose_name='Lien du carroussel pour la pub')),
                ('created_at', models.DateField(verbose_name='Date de debut')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('draft', models.BooleanField(default=False, verbose_name='Est en brouillard ?')),
                ('is_welcome', models.BooleanField(default=False, verbose_name='Carroussel de bienvenue ?')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carrouselles',
                'verbose_name_plural': 'Les carrouselles',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titre de la vidéo')),
                ('category', models.CharField(default='', max_length=200, verbose_name='Catégorie')),
                ('image', models.ImageField(blank=True, upload_to='podcast/images/', verbose_name='Image de couverture')),
                ('video_file', models.FileField(blank=True, help_text='Fichier vidéo', upload_to='videos/', verbose_name='Fichier vidéo')),
                ('video_url', models.URLField(blank=True, help_text='URL de la vidéo Youtube ou Vimeo', verbose_name='URL de la vidéo')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Les vidéos',
                'ordering': ['-created_at'],
            },
        ),
    ]
