# Generated by Django 5.1.6 on 2025-07-24 11:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0006_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
