# Generated by Django 5.1.6 on 2025-07-24 11:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0007_alter_about_text_alter_slider_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldata',
            options={'verbose_name': 'Donnée personnelle', 'verbose_name_plural': ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte sur les données personnelles')},
        ),
    ]
