# Generated by Django 5.1.6 on 2025-07-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0008_alter_personaldata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldata',
            options={'verbose_name': 'Donnée personnelle', 'verbose_name_plural': 'Texte sur les données personnelles'},
        ),
    ]
