# Generated by Django 5.2.4 on 2025-07-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0009_alter_personaldata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, upload_to='podcast/images/', verbose_name='Image de couverture'),
        ),
    ]
