# Generated by Django 5.1.6 on 2025-06-07 21:25
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("site", "Website Carousel"),
                            ("mobile", "Mobile Carousel"),
                            ("popup", "Popup"),
                        ],
                        max_length=20,
                        verbose_name="Support Type",
                    ),
                ),
                (
                    "unit_price",
                    models.PositiveIntegerField(
                        help_text="Price in FCFA", verbose_name="Unit Price"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is the offer active?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Visible on the platform",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "audio_durations",
                    models.CharField(
                        blank=True,
                        help_text="Duration of audio spots (e.g., 20s, 30s)",
                        max_length=10,
                        verbose_name="Audio Durations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising Offer",
                "verbose_name_plural": "Advertising Offers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OfferCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Offer Category",
                "verbose_name_plural": "Offer Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AdPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Placement Name"),
                ),
                (
                    "available_slots",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Available Slots"
                    ),
                ),
                (
                    "price_per_slot",
                    models.PositiveIntegerField(verbose_name="Price per Slot"),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="tarif.advertisingoffer",
                        verbose_name="Advertising Offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Placement",
                "verbose_name_plural": "Ad Placements",
            },
        ),
        migrations.AddField(
            model_name="advertisingoffer",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="tarif.offercategory",
                verbose_name="Category",
            ),
        ),
        migrations.CreateModel(
            name="OfferOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Option Name")),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                (
                    "additional_price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra price for this option",
                        verbose_name="Additional Price",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="tarif.advertisingoffer",
                        verbose_name="Advertising Offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Option",
                "verbose_name_plural": "Offer Options",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Reference"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("amount", models.PositiveIntegerField(verbose_name="Amount (FCFA)")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Paid")),
                ("cart", models.JSONField(default=list, verbose_name="Cart Items")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Transaction ID"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Amount")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REFUSED", "Refused"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Response Data"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="tarif.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
