# Generated by Django 5.1.6 on 2025-07-24 11:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingoffer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Description de l'actualité"),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Description de l'actualité"),
        ),
    ]
