# Generated by Django 5.2.4 on 2025-07-28 14:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'emission")),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name="Image de l'emission")),
                ('presentator', models.CharField(blank=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Brouillon')),
                ('slug_uri', models.SlugField(max_length=200, verbose_name='Url converted ?')),
            ],
            options={
                'verbose_name': 'Emission',
                'verbose_name_plural': 'Les émissions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FridayEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'edito")),
                ('image', models.FileField(upload_to='images/')),
                ('presentator', models.CharField(blank=True, max_length=200, verbose_name='Nom du presentateur')),
                ('complete_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('incomplete_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=500, verbose_name='Url du fichier audio')),
                ('complete_audio_file', models.FileField(blank=True, upload_to='images/', verbose_name='Fichier audio complet')),
                ('incomplete_audio_file', models.FileField(blank=True, upload_to='images/', verbose_name='Fichier audio incomplet')),
                ('created_at', models.DateField(auto_now=True)),
                ('dateline', models.DateField()),
                ('video_link', models.URLField(blank=True, verbose_name='Lien de la video youtube')),
                ('slug_uri', models.SlugField(max_length=200, verbose_name='Url converted ?')),
            ],
            options={
                'verbose_name': 'Edito',
                'verbose_name_plural': 'Les editos du vendredi',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du podcast')),
                ('intitule', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre ou résumé du podcast')),
                ('auteur', models.CharField(default='Inconnu', max_length=100, verbose_name='Auteur du podcast')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='podcast/fichiers/', verbose_name='Fichier audio ou vidéo')),
                ('image', models.ImageField(blank=True, upload_to='podcast/images/', verbose_name='Image de couverture')),
                ('audio_url', models.URLField(blank=True, verbose_name='Lien externe (optionnel)')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Date de création')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emission.categorie', verbose_name='Catégorie du podcast')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'épisode")),
                ('auteur', models.CharField(max_length=150, verbose_name='Auteur')),
                ('audio_url', models.URLField(blank=True, verbose_name="URL de l'audio")),
                ('fichier', models.FileField(upload_to='poadcast/episodes/', verbose_name='Fichier audio/vidéo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='emission.poadcast')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'emission")),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name="Image de l'emission")),
                ('presentator', models.CharField(blank=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Brouillon')),
                ('slug_uri', models.SlugField(max_length=200, verbose_name='Url converted ?')),
                ('video_link', models.URLField(blank=True)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sousEmission', to='emission.emission')),
            ],
            options={
                'verbose_name': 'Sous emission',
                'verbose_name_plural': 'Les sous emissions',
                'ordering': ['created_at'],
            },
        ),
    ]
