# Generated by Django 5.1.6 on 2025-07-24 11:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subemission',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
