# Generated by Django 5.2.4 on 2025-07-31 13:41

import evenslide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.CharField(db_index=True, default=evenslide.models.ulid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.CharField(db_index=True, default=evenslide.models.ulid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fridayeditorial',
            name='id',
            field=models.CharField(db_index=True, default=evenslide.models.ulid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poadcast',
            name='id',
            field=models.CharField(db_index=True, default=evenslide.models.ulid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
