# Generated by Django 5.1.6 on 2025-07-24 11:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0002_alter_emission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridayeditorial',
            name='complete_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fridayeditorial',
            name='incomplete_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
