# Generated by Django 5.2.4 on 2025-07-31 15:14

import evenslide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0002_alter_categorie_id_alter_episode_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, upload_to='podcast/images/', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='emission',
            name='id',
            field=models.CharField(db_index=True, default=evenslide.models.ulid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subemission',
            name='id',
            field=models.CharField(db_index=True, default=evenslide.models.ulid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
