# Generated by Django 5.2.4 on 2025-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0003_alter_fridayeditorial_complete_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poadcast',
            options={'ordering': ['-created_at'], 'verbose_name': 'Podcast', 'verbose_name_plural': 'Podcasts'},
        ),
        migrations.RemoveField(
            model_name='poadcast',
            name='audio',
        ),
        migrations.AddField(
            model_name='poadcast',
            name='auteur',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Auteur du podcast'),
        ),
        migrations.AddField(
            model_name='poadcast',
            name='categorie',
            field=models.CharField(choices=[('education', 'Éducation'), ('societe', 'Société'), ('actualite', 'Actualité & Politique'), ('business', 'Business & Entrepreneuriat'), ('culture', 'Culture & Art'), ('developpement', 'Développement personnel'), ('crime', 'True Crime & Enquêtes'), ('fiction', 'Fiction & Histoire'), ('technologie', 'Technologie & Gaming'), ('humour', 'Humour & Divertissement'), ('relations', 'Relations & Famille'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie du podcast'),
        ),
        migrations.AddField(
            model_name='poadcast',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='podcast/fichiers/', verbose_name='Fichier audio ou vidéo'),
        ),
        migrations.AddField(
            model_name='poadcast',
            name='intitule',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sous-titre ou résumé du podcast'),
        ),
        migrations.AlterField(
            model_name='poadcast',
            name='audio_url',
            field=models.URLField(blank=True, verbose_name='Lien externe (optionnel)'),
        ),
        migrations.AlterField(
            model_name='poadcast',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='poadcast',
            name='image',
            field=models.ImageField(blank=True, upload_to='podcast/images/', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='poadcast',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du podcast'),
        ),
    ]
