# Generated by Django 5.2.4 on 2025-07-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0004_alter_poadcast_options_remove_poadcast_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'épisode")),
                ('auteur', models.CharField(max_length=150, verbose_name='Auteur')),
                ('audio_url', models.URLField(blank=True, verbose_name="URL de l'audio")),
                ('fichier', models.FileField(upload_to='poadcast/episodes/', verbose_name='Fichier audio/vidéo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='emission.poadcast')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
